name: testing         #name of that workflow
on : push           #when push the code run workflow

jobs:
  test_project:
    runs-on: ubuntu-latest   #run on VM
    steps:
    - uses: actions/checkout@v2  #github action/chekout
    - name: Run Django unit tests
      run: |
        pi3 install --user django
        python3 manage.py test
